import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/header";
import Footer from "./components/layout/footer";
const inter = Inter({ subsets: ["latin"] });
import CssBaseline from '@mui/material/CssBaseline';
import "../../public/scss/main.scss";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <CssBaseline />
        {children}
        <Footer />
      </body>
    </html>
  );
}
